package com.capgemini.quiz.day5;
class A 
{ 
//public A()
//	{
		
//	}
    public A(String s)  
    { 
        System.out.print("A"); 
    } 
} 
public class Quiz4 extends A{
	 public Quiz4(String s)  
	    { 
	        System.out.print("B"); 
	    } 
	    public static void main(String[] args)  
	    { 
	        new Quiz4("C"); 
	        System.out.println(" "); 
	    } 

}
//The implied super() call in B’s constructor cannot be satisfied 
//because there isn’t a no-arg constructor in A. A default, 
//no-arg constructor is generated by the compiler only 
//if the class has no constructor defined explicitly.
